### ISSUE TITLE
yran build issue

### ISSUE THREAD

**Issue by dineshpanchal93** [The-Commit-Company/expense-tracker#1]
(frappe) (base) dinesh@Dineshs-MacBook-Air expense_tracker % yarn build
yarn run v1.22.19
$ cd expenses && yarn build
$ vite build --base=/assets/expense_tracker/expenses/ && yarn copy-html-entry
/bin/sh: vite: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(frappe) (base) dinesh@Dineshs-MacBook-Air expense_tracker %

**Comment by dineshpanchal93** [comment]
@nikkothari22 we tried with our app followed with youtube video Tutorial we are also getting same error.

**Comment by nikkothari22** [comment]
Run `bench setup requirements` before. Vite hasn't been installed

**Comment by dineshpanchal93** [comment]
@nikkothari22 Yes that is resolved but still page is not loading. it says 404 also i tried this app install using frappe cloud but still /expenses it says page not found.

**Comment by nikkothari22** [comment]
@dineshpanchal93 on your local environment, you need to start the React web server by going into the expense_tracker app and run yarn dev.

If you want to view the app on your Frappe site, run bench build. 

On Frappe Cloud, make sure to deploy the app to your private bench and site after adding it.

**Comment by dineshpanchal93** [comment]
@nikkothari22 tried everything but didn't work.

All the files is being getting loaded but socket.io is not working.

Any suggestion !!

**Comment by nikkothari22** [comment]
@dineshpanchal93 

Make sure you have the following in your React app for your local environment:
- A .env.local file with the following environment variables: `VITE_SOCKET_PORT=9000` (change the port number according to your local setup). and `VITE_BASE_PATH=''` .

On Frappe Cloud, did you deploy the app (it's after adding the app)? And can you share some screenshots because I cannot debug without them.

**Comment by dineshpanchal93** [comment]
@nikkothari22  Sure. wil do that, also i have added you in collab ,  custom app that i have created.

https://github.com/dineshpanchal93/bepl_ui/invitations
