### ISSUE TITLE
useFrappeDocTypeEventListener not working

### ISSUE THREAD

**Issue by Linny3D** [The-Commit-Company/expense-tracker#2]
The Event never gets caught and consequently the mutate() function is not executed.

**Description:**
As the user sameedhasan2171 in the Youtube comments already mentioned, the Event never gets caught. Same behaviour with the original github code.

**Browser:** Chrome  115.0.5790.102
**OS:** Linux 64-Bit
**Dev-OS:** Linux 64-Bit

**Steps to reproduce:**

1.  Click the 'Add' Button to create a new expense
2.  Fill in the form
3.  Click 'Save'

**Actual Result:** The new expense dataset has been created, but the page does not refresh
**Expected Result:** After the expense has been created the Event should have been caught by the `useFrappeDocTypeEventListener` and the `mutate()` function should have been executed to fetch the new data and update the page.

**File:** ExpenseListTab.tsx
**Line:** 22-27

useFrappeDocTypeEventListener('Expense Record', (d) => {
        console.log("Event", d)
        if (d.doctype === "Expense Record") {
            mutate()
        }
    })

**package.json for version info:**
{
  "name": "expenses",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build --base=/assets/expense_tracker/expenses/ && yarn copy-html-entry",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview",
    "copy-html-entry": "cp ../expense_tracker/public/expenses/index.html ../expense_tracker/www/expenses.html"
  },
  "dependencies": {
    "@chakra-ui/react": "^2.8.0",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "framer-motion": "^10.13.2",
    "frappe-react-sdk": "^1.2.8",
    "react": "^18.2.0",
    "react-datepicker": "^4.16.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.45.2",
    "react-router-dom": "^6.14.2",
    "socket.io-client": "^4.5.1"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "@vitejs/plugin-react": "^4.0.3",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "postcss": "^8.4.27",
    "tailwindcss": "^3.3.3",
    "typescript": "^5.1.6",
    "vite": "^4.4.5"
  }
}

**Comment by Linny3D** [comment]
### Temporary workaround to continue from the youtube tutorial:
Add the mutate() function as a prop to the <AddExpenseRecord> tag in `ExpenseListTab.tsx` like so:

`<AddExpenseRecord isOpen={isOpen} onClose={onClose} mutate={mutate}/>`

In the `AddExpenseRecord.tsx` change the declaration of the `AddExpenseRecord` function like so:

`export const AddExpenseRecord = ({ isOpen, onClose,mutate }: Props) => {`

Finally change the createDoc function to the following:
(Hint: This is the code at 1:25:06 from the youtube tutorial. Not the final Github code !!!)

```
createDoc("Expense Record", data).then(() => {
      mutate();
      onClose();
    });
```

**Result:** As expected the page gets updated after the new record was successfully created.

**Comment by nikkothari22** [comment]
Hey @Linny3D 

We use the useFrappeDoctypeEventListener hook on our apps and they work (almost). We have noticed that sometimes there might be an issue with the event listener (especially if two tabs or components are listening to the same event with the same user - this could also happen if the list is open on both the Frappe and the React interface since both subscribe to the same event). 

Regardless, that's a Frappe framework issue. I would recommend explicitly refreshing the list/data if you have an event where you know that the list needs to be updated (like adding a record in this example).

**Comment by Linny3D** [comment]
Hey @nikkothari22 
thanks for the reply. So i will do it the "old-fashioned" way and keep updating the page explicitly. No Problem  ;)
Since this seems to be a problem on the Frappe side, i think we can close this issue here.

Thank you for the great project. Keep up the good work. This is really helpful.
